### PR TITLE
added Typescript typings

### PR DESCRIPTION
**Pull request by jtlapp**
Here are Typescript typings for this helpful little module.

I sought out to ease the pain of asserting thrown errors in `chai`, decided that the main problem with existing solutions was having to wire everything up from multiple packages, and so planned to write my own solution. I thought of a name for it, searched NPM for a package of that name, and voilà! -- your package popped up.

You had already solve my problem.

Almost, anyway. I'm working in Typescript, and I wanted a solution that required installing just one package to do the job. If we add these typings to the package, I've got exactly what I wanted.

Thanks for considering my request! And for already having implemented the thing!

### CODE REVIEW

**Comment by RangerMauve** [comment]
Thank you for the PR! I've been getting into typescript too, so this will help me out when I need to test promise stuff! :D

I've published it in v1.1.1

**Comment by jtlapp** [comment]
Woo! That was quick. Thanks so much!

Good luck with the TS. The basic language is straightforward enough, but sheesh, the complexity necessary to describe the variety of Javascript types is absolutely insane!

**Comment by RangerMauve** [comment]
Hah, tell me about it. 😅 I'm working on [async-iterator-hof](https://github.com/RangerMauve/async-iterator-hof) which requires a bunch of messing around with generics, and I've already run into [issues](https://github.com/RangerMauve/async-iterator-hof/blob/master/index.ts#L286) with it not being smart enough for some of the stuff I want to do.

**Comment by jtlapp** [comment]
Looks like a fun project! I'm working on several. This week it's a minimalist/extensible ORM for Typescript. TypeORM doesn't provide clean enough integration between raw SQL and object mapping, and Objection.js doesn't provide clear enough exposure of how methods map to SQL for case-by-case evaluation of when to use the ORM and when to go raw.

**Comment by jtlapp** [comment]
Feel free to shoot me Typescript questions. I've learned a boatload in the past two months. I've been doing quite a bit with generics too. arachnojoe@gmail.com

**Comment by jtlapp** [comment]
I peeked at `AsyncIteraterHof`. I'm not quite sure what problem you're facing.

The instance of `AsyncIteraterHof<T>` provides the `T` type. The `other` parameter passed to `zip()` provides the `R` type. Were you expecting them to have to be the same type?

**Comment by jtlapp** [comment]
I do see something funky [here](https://github.com/RangerMauve/async-iterator-hof/blob/master/index.ts#L274):

```ts
async function* zip<RR>(source: AsyncIterable<T>) : AsyncIterable<[T, RR]>
```

`RR` here necessarily has type `any`, because it can't be inferred from any function parameter in this signature (and because it defaults to `any`). No inference occurs from return values.

**Comment by RangerMauve** [comment]
@jtlapp I want `RR` to just be `R`, but Typescript won't let me use it because it can't link the two types together.

**Comment by jtlapp** [comment]
Are you saying this line won't work?

```ts
async function* zip(source: AsyncIterable<T>) : AsyncIterable<[T, R]>
```

Or are you saying you want something like this?

```ts
async function* zip<RR=R>(source: AsyncIterable<T>) : AsyncIterable<[T, RR]>
```

**Comment by RangerMauve** [comment]
My code used to look like 

```typescript
zip<R>(other: AsyncIterable<R>): AsyncIteraterHof<[T, R]> {
	async function* zip<R>(source: AsyncIterable<T>) : AsyncIterable<[T, R]> {
		// etc
	}
}
```

But it wasn't letting me use the same R. Would having `RR=R` in the generator be enough to make it stop complaining?

**Comment by jtlapp** [comment]
I'll look at that, but first thing that pops out is the equivalence of your last snippet to this:

```ts
zip<R>(other: AsyncIterable<R>): AsyncIteraterHof<[T, R]> {
	async function* zip(source: AsyncIterable<T>) : AsyncIterable<[T, any]> {
```

... because your nested `zip<R>` defines a new generic different from the outer `zip<R>`.

**Comment by RangerMauve** [comment]
Yeah, I added the `RR` part because I was trying to use [zip<R>()](https://github.com/RangerMauve/async-iterator-hof/blob/master/index.ts#L298) further down in the function so that `RR` would effectively be R. But it didn't really understand it.

**Comment by jtlapp** [comment]
Oh, your last line does assign `RR` the value `R` from the outer `zip<R>()`, but `R` and `T` are still independent types.

```ts
return new AsyncIteraterHof<[T, R]>(zip<R>(this.source));
```

As long as `T` derives from the class and `R` derives from the function parameter, there is nothing you can do to force them to be of the same type. If you want pairings of the same type, somewhere you'll need to have `[R, R]` or `[T, T]`. (Still confused about the actual problem...)

**Comment by jtlapp** [comment]
This should give you `[T, R]`, if that's what you're going for:

```ts

	zip<R>(other: AsyncIterable<R>): AsyncIteraterHof<[T, R]> {
		async function* zip(source: AsyncIterable<T>) : AsyncIterable<[T, R]> {
			const iterator1 = source[Symbol.asyncIterator]();
			const iterator2 = other[Symbol.asyncIterator]();

			try {
				let isDone = false;
				while(!isDone) {
					let result1 = await iterator1.next();
					if(result1.done) return;
					let result2 = await iterator2.next();
					if(result2.done) return;

					// Should have types [T, R]
					yield [result1.value, result2.value];
				}
			} finally {
				if(iterator1.return)
					iterator1.return();
				if(iterator2.return)
					iterator2.return();
			}
		}

		return new AsyncIteraterHof<[T, R]>(zip(this.source));
	}
```

**Comment by RangerMauve** [comment]
Yeah, I might have been over-complicating it. I'll try your code later to see if that solves my issues. I think I still don't fully get when to pass in the generic for methods. You have a `zip<R>` on the outside with works, but the `async function* zip` isn't taking an `<R>`, so I'm not sure how it knows what `R` is when it outputs `[T, R]`

**Comment by jtlapp** [comment]
The generics are just block-scoped types. So `R` in the outer `function zip<R>()` holds for the entire outer `zip()` function -- until (and if) you redefine it for a nested block.

Function generics are mainly used to infer types from provided input parameters. Once inferred, use them anywhere you need to in the function.

**Comment by RangerMauve** [comment]
Oh, I didn't know they were block scoped. :P

**Pull request merged**
